services:
  backend:
    build: ./backend
    container_name: btrust-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev

  frontend:
    build: .
    container_name: btrust-frontend
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=https://btrust-backend-production.up.railway.app  # Your backend URL
    command: npm run dev
    depends_on:
      - backend