name: CI-CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Backend Image
        run: docker build -t btrust-backend ./backend

      - name: Build Frontend Image
        run: docker build -t btrust-frontend .

      - name: Run Tests (Backend)
        run: docker-compose run backend npm test || true  # Allows failure if tests are missing

      - name: Run Tests (Frontend)
        run: docker-compose run frontend npm test || true  # Allows failure if tests are missing